def team_results(race_results):
    team_points = dict()
    standings = race_results['standings']
    for s in standings:
        team_points.setdefault(s['team'],0)
        team_points[s['team']] += s['pts']

    ordered_points = list(sorted(team_points.items(), key=lambda i: i[1], reverse=True))
    for k,v in ordered_points:
        print(f'{k} {v}')

race_results = {'date': '09 Jun 2019', 'location': 'Circuit Gilles-Villeneuve, MontrÃ©al', 'race': 'FORMULA 1 PIRELLI GRAND PRIX DU CANADA 2019', 'standings': [{'pos': '1', 'laps': 44, 'pts': 25, 'time': '1:29:07.084', 'driver': 'Lewis Hamilton', 'team': 'Mercedes'}, {'pos': '2', 'laps': 5, 'pts': 18, 'time': '+3.658s', 'driver': 'Sebastian Vettel', 'team': 'Ferrari'}, {'pos': '3', 'laps': 16, 'pts': 15, 'time': '+4.696s', 'driver': 'Charles Leclerc', 'team': 'Ferrari'}, {'pos': '4', 'laps': 77, 'pts': 13, 'time': '+51.043s', 'driver': 'Valtteri Bottas', 'team': 'Mercedes'}, {'pos': '5', 'laps': 33, 'pts': 10, 'time': '+57.655s', 'driver': 'Max Verstappen', 'team': 'Red Bull Racing Honda'}, {'pos': '6', 'laps': 3, 'pts': 8, 'time': '+1 lap', 'driver': 'Daniel Ricciardo', 'team': 'Renault'}, {'pos': '7', 'laps': 27, 'pts': 6, 'time': '+1 lap', 'driver': 'Nico Hulkenberg', 'team': 'Renault'}, {'pos': '8', 'laps': 10, 'pts': 4, 'time': '+1 lap', 'driver': 'Pierre Gasly', 'team': 'Red Bull Racing Honda'}, {'pos': '9', 'laps': 18, 'pts': 2, 'time': '+1 lap', 'driver': 'Lance Stroll', 'team': 'Racing Point BWT Mercedes'}, {'pos': '10', 'laps': 26, 'pts': 1, 'time': '+1 lap', 'driver': 'Daniil Kvyat', 'team': 'Scuderia Toro Rosso Honda'}, {'pos': '11', 'laps': 55, 'pts': 0, 'time': '+1 lap', 'driver': 'Carlos Sainz', 'team': 'McLaren Renault'}, {'pos': '12', 'laps': 11, 'pts': 0, 'time': '+1 lap', 'driver': 'Sergio Perez', 'team': 'Racing Point BWT Mercedes'}, {'pos': '13', 'laps': 99, 'pts': 0, 'time': '+1 lap', 'driver': 'Antonio Giovinazzi', 'team': 'Alfa Romeo Racing Ferrari'}, {'pos': '14', 'laps': 8, 'pts': 0, 'time': '+1 lap', 'driver': 'Romain Grosjean', 'team': 'Haas Ferrari'}, {'pos': '15', 'laps': 7, 'pts': 0, 'time': '+1 lap', 'driver': 'Kimi RÃ¤ikkÃ¶nen', 'team': 'Alfa Romeo Racing Ferrari'}, {'pos': '16', 'laps': 63, 'pts': 0, 'time': '+2 laps', 'driver': 'George Russell', 'team': 'Williams Mercedes'}, {'pos': '17', 'laps': 20, 'pts': 0, 'time': '+2 laps', 'driver': 'Kevin Magnussen', 'team': 'Haas Ferrari'}, {'pos': '18', 'laps': 88, 'pts': 0, 'time': '+3 laps', 'driver': 'Robert Kubica', 'team': 'Williams Mercedes'}, {'pos': 'NC', 'laps': 23, 'pts': 0, 'time': 'DNF', 'driver': 'Alexander Albon', 'team': 'Scuderia Toro Rosso Honda'}, {'pos': 'NC', 'laps': 4, 'pts': 0, 'time': 'DNF', 'driver': 'Lando Norris', 'team': 'McLaren Renault'}]}

team_results(race_results)